// This file is auto-generated by @hey-api/openapi-ts

export type CarCreate = {
    seat_count?: number;
    passengers?: Array<Passenger> | null;
};

export type CarPublic = {
    seat_count?: number;
    passengers?: Array<User> | null;
    id: number;
    trip_id: number;
    owner: User;
};

export type DtoCarPublic = {
    data: CarPublic;
};

export type DtoPassengerCreate = {
    data: PassengerCreate;
};

export type DtoSortedUsersResponse = {
    data: SortedUsersResponse;
};

export type DtoTripPublic = {
    data: TripPublic;
};

export type DtoUser = {
    data: User;
};

export type DtoBool = {
    data: boolean;
};

export type DtoListCarPublic = {
    data: Array<CarPublic>;
};

export type DtoListPassenger = {
    data: Array<Passenger>;
};

export type DtoListTripPublic = {
    data: Array<TripPublic>;
};

export type DtoListUser = {
    data: Array<User>;
};

export type DeepLink = {
    deep_link: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type Passenger = {
    seat_position: number;
    user_id: string;
    car_id: number;
};

export type PassengerCreate = {
    seat_position: number;
};

export type SortedUsersResponse = {
    accepted: Array<User>;
    pending: Array<User>;
    uncertain: Array<User>;
    declined: Array<User>;
};

export type TripCreate = {
    title: string;
    start_date: string;
    end_date: string;
    mountain: string;
    desc: string | null;
};

export type TripParticipationRsvp = {
    rsvp?: string | null;
    paid?: number | null;
};

export type TripPublic = {
    title: string;
    start_date: string;
    end_date: string;
    mountain: string;
    desc: string | null;
    id: number;
    owner: User;
};

export type TripUpdate = {
    title?: string | null;
    start_date?: string | null;
    end_date?: string | null;
    mountain?: string | null;
    desc?: string | null;
};

export type User = {
    id: string;
    phone: string;
    firstname: string | null;
    lastname: string | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type MainApiV1GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/';
};

export type MainApiV1GetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type MainApiV1GetResponse = MainApiV1GetResponses[keyof MainApiV1GetResponses];

export type GetUsersApiV1UsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type GetUsersApiV1UsersGetResponses = {
    /**
     * Successful Response
     */
    200: DtoListUser;
};

export type GetUsersApiV1UsersGetResponse = GetUsersApiV1UsersGetResponses[keyof GetUsersApiV1UsersGetResponses];

export type GetUserByIdApiV1UsersUserIdGetData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetUserByIdApiV1UsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdApiV1UsersUserIdGetError = GetUserByIdApiV1UsersUserIdGetErrors[keyof GetUserByIdApiV1UsersUserIdGetErrors];

export type GetUserByIdApiV1UsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: DtoUser;
};

export type GetUserByIdApiV1UsersUserIdGetResponse = GetUserByIdApiV1UsersUserIdGetResponses[keyof GetUserByIdApiV1UsersUserIdGetResponses];

export type GetTripsApiV1TripsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/trips/';
};

export type GetTripsApiV1TripsGetResponses = {
    /**
     * Successful Response
     */
    200: DtoListTripPublic;
};

export type GetTripsApiV1TripsGetResponse = GetTripsApiV1TripsGetResponses[keyof GetTripsApiV1TripsGetResponses];

export type CreateTripApiV1TripsPostData = {
    body: TripCreate;
    path?: never;
    query?: never;
    url: '/api/v1/trips/';
};

export type CreateTripApiV1TripsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTripApiV1TripsPostError = CreateTripApiV1TripsPostErrors[keyof CreateTripApiV1TripsPostErrors];

export type CreateTripApiV1TripsPostResponses = {
    /**
     * Successful Response
     */
    200: DtoTripPublic;
};

export type CreateTripApiV1TripsPostResponse = CreateTripApiV1TripsPostResponses[keyof CreateTripApiV1TripsPostResponses];

export type DeleteTripApiV1TripsTripIdDeleteData = {
    body?: never;
    path: {
        trip_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type DeleteTripApiV1TripsTripIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTripApiV1TripsTripIdDeleteError = DeleteTripApiV1TripsTripIdDeleteErrors[keyof DeleteTripApiV1TripsTripIdDeleteErrors];

export type DeleteTripApiV1TripsTripIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteTripApiV1TripsTripIdDeleteResponse = DeleteTripApiV1TripsTripIdDeleteResponses[keyof DeleteTripApiV1TripsTripIdDeleteResponses];

export type GetTripApiV1TripsTripIdGetData = {
    body?: never;
    path: {
        trip_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type GetTripApiV1TripsTripIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTripApiV1TripsTripIdGetError = GetTripApiV1TripsTripIdGetErrors[keyof GetTripApiV1TripsTripIdGetErrors];

export type GetTripApiV1TripsTripIdGetResponses = {
    /**
     * Successful Response
     */
    200: DtoTripPublic;
};

export type GetTripApiV1TripsTripIdGetResponse = GetTripApiV1TripsTripIdGetResponses[keyof GetTripApiV1TripsTripIdGetResponses];

export type UpdateTripApiV1TripsTripIdPatchData = {
    body: TripUpdate;
    path: {
        trip_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type UpdateTripApiV1TripsTripIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTripApiV1TripsTripIdPatchError = UpdateTripApiV1TripsTripIdPatchErrors[keyof UpdateTripApiV1TripsTripIdPatchErrors];

export type UpdateTripApiV1TripsTripIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DtoTripPublic;
};

export type UpdateTripApiV1TripsTripIdPatchResponse = UpdateTripApiV1TripsTripIdPatchResponses[keyof UpdateTripApiV1TripsTripIdPatchResponses];

export type GetCarsForTripApiV1TripsTripIdCarsGetData = {
    body?: never;
    path: {
        trip_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/cars/';
};

export type GetCarsForTripApiV1TripsTripIdCarsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCarsForTripApiV1TripsTripIdCarsGetError = GetCarsForTripApiV1TripsTripIdCarsGetErrors[keyof GetCarsForTripApiV1TripsTripIdCarsGetErrors];

export type GetCarsForTripApiV1TripsTripIdCarsGetResponses = {
    /**
     * Successful Response
     */
    200: DtoListCarPublic;
};

export type GetCarsForTripApiV1TripsTripIdCarsGetResponse = GetCarsForTripApiV1TripsTripIdCarsGetResponses[keyof GetCarsForTripApiV1TripsTripIdCarsGetResponses];

export type CreateCarApiV1TripsTripIdCarsPostData = {
    body: CarCreate;
    path: {
        trip_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/cars/';
};

export type CreateCarApiV1TripsTripIdCarsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateCarApiV1TripsTripIdCarsPostError = CreateCarApiV1TripsTripIdCarsPostErrors[keyof CreateCarApiV1TripsTripIdCarsPostErrors];

export type CreateCarApiV1TripsTripIdCarsPostResponses = {
    /**
     * Successful Response
     */
    200: DtoCarPublic;
};

export type CreateCarApiV1TripsTripIdCarsPostResponse = CreateCarApiV1TripsTripIdCarsPostResponses[keyof CreateCarApiV1TripsTripIdCarsPostResponses];

export type DeleteCarApiV1TripsTripIdCarsCarIdDeleteData = {
    body?: never;
    path: {
        trip_id: number;
        car_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/cars/{car_id}';
};

export type DeleteCarApiV1TripsTripIdCarsCarIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCarApiV1TripsTripIdCarsCarIdDeleteError = DeleteCarApiV1TripsTripIdCarsCarIdDeleteErrors[keyof DeleteCarApiV1TripsTripIdCarsCarIdDeleteErrors];

export type DeleteCarApiV1TripsTripIdCarsCarIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteCarApiV1TripsTripIdCarsCarIdDeleteResponse = DeleteCarApiV1TripsTripIdCarsCarIdDeleteResponses[keyof DeleteCarApiV1TripsTripIdCarsCarIdDeleteResponses];

export type GetCarByIdApiV1TripsTripIdCarsCarIdGetData = {
    body?: never;
    path: {
        trip_id: number;
        car_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/cars/{car_id}';
};

export type GetCarByIdApiV1TripsTripIdCarsCarIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCarByIdApiV1TripsTripIdCarsCarIdGetError = GetCarByIdApiV1TripsTripIdCarsCarIdGetErrors[keyof GetCarByIdApiV1TripsTripIdCarsCarIdGetErrors];

export type GetCarByIdApiV1TripsTripIdCarsCarIdGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetCarByIdApiV1TripsTripIdCarsCarIdGetResponse = GetCarByIdApiV1TripsTripIdCarsCarIdGetResponses[keyof GetCarByIdApiV1TripsTripIdCarsCarIdGetResponses];

export type GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetData = {
    body?: never;
    path: {
        trip_id: number;
        car_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/cars/{car_id}/passengers';
};

export type GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetError = GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetErrors[keyof GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetErrors];

export type GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetResponses = {
    /**
     * Successful Response
     */
    200: DtoListPassenger;
};

export type GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetResponse = GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetResponses[keyof GetPassengersApiV1TripsTripIdCarsCarIdPassengersGetResponses];

export type AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostData = {
    body: PassengerCreate;
    path: {
        trip_id: number;
        car_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/cars/{car_id}/passengers';
};

export type AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostError = AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostErrors[keyof AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostErrors];

export type AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostResponses = {
    /**
     * Successful Response
     */
    200: DtoPassengerCreate;
};

export type AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostResponse = AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostResponses[keyof AddPassengerApiV1TripsTripIdCarsCarIdPassengersPostResponses];

export type GetInvitedUsersApiV1TripsTripIdInvitesGetData = {
    body?: never;
    path: {
        trip_id: number;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/invites';
};

export type GetInvitedUsersApiV1TripsTripIdInvitesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetInvitedUsersApiV1TripsTripIdInvitesGetError = GetInvitedUsersApiV1TripsTripIdInvitesGetErrors[keyof GetInvitedUsersApiV1TripsTripIdInvitesGetErrors];

export type GetInvitedUsersApiV1TripsTripIdInvitesGetResponses = {
    /**
     * Successful Response
     */
    200: DtoSortedUsersResponse;
};

export type GetInvitedUsersApiV1TripsTripIdInvitesGetResponse = GetInvitedUsersApiV1TripsTripIdInvitesGetResponses[keyof GetInvitedUsersApiV1TripsTripIdInvitesGetResponses];

export type RsvpApiV1TripsTripIdInvitesUserIdPatchData = {
    body: TripParticipationRsvp;
    path: {
        trip_id: number;
        user_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/invites/{user_id}';
};

export type RsvpApiV1TripsTripIdInvitesUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RsvpApiV1TripsTripIdInvitesUserIdPatchError = RsvpApiV1TripsTripIdInvitesUserIdPatchErrors[keyof RsvpApiV1TripsTripIdInvitesUserIdPatchErrors];

export type RsvpApiV1TripsTripIdInvitesUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: DtoBool;
};

export type RsvpApiV1TripsTripIdInvitesUserIdPatchResponse = RsvpApiV1TripsTripIdInvitesUserIdPatchResponses[keyof RsvpApiV1TripsTripIdInvitesUserIdPatchResponses];

export type InviteUserApiV1TripsTripIdInvitesUserIdPostData = {
    body: DeepLink;
    path: {
        trip_id: number;
        user_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/invites/{user_id}';
};

export type InviteUserApiV1TripsTripIdInvitesUserIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InviteUserApiV1TripsTripIdInvitesUserIdPostError = InviteUserApiV1TripsTripIdInvitesUserIdPostErrors[keyof InviteUserApiV1TripsTripIdInvitesUserIdPostErrors];

export type InviteUserApiV1TripsTripIdInvitesUserIdPostResponses = {
    /**
     * Successful Response
     */
    201: DtoBool;
};

export type InviteUserApiV1TripsTripIdInvitesUserIdPostResponse = InviteUserApiV1TripsTripIdInvitesUserIdPostResponses[keyof InviteUserApiV1TripsTripIdInvitesUserIdPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};